# Generated by Django 3.2.9 on 2021-11-27 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=10, null=True, verbose_name='CardStatus')),
                ('max_people_count', models.IntegerField(default=1, verbose_name='Card max count of people')),
                ('current_people_count', models.IntegerField(default=0, verbose_name='Card current count of people')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='CardStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'CardStatus',
                'verbose_name_plural': 'CardStatuses',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NotificationName')),
            ],
            options={
                'verbose_name': 'NotificationType',
                'verbose_name_plural': 'NotificationTypes',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Tag name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='User photo')),
                ('status', models.CharField(blank=True, max_length=150, null=True, verbose_name='User status')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About user')),
                ('contact', models.ManyToManyField(blank=True, related_name='_ShumiApp_profile_contact_+', to='ShumiApp.Profile', verbose_name='Contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_to', to='ShumiApp.profile', verbose_name='Profile')),
                ('notification_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ShumiApp.notificationtype', verbose_name='Notification type')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_from', to='ShumiApp.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Complaint date')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShumiApp.profile', verbose_name='Complaint author')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
            },
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(verbose_name='Is main')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Image')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShumiApp.card', verbose_name='Card')),
            ],
            options={
                'verbose_name': 'Card image',
                'verbose_name_plural': 'Card images',
            },
        ),
        migrations.CreateModel(
            name='CardArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='Card archive status')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShumiApp.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Card archive',
                'verbose_name_plural': 'Card archives',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='archive',
            field=models.ManyToManyField(blank=True, to='ShumiApp.CardArchive', verbose_name='Card archive'),
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ShumiApp.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='card',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ShumiApp.complaint', verbose_name='Complaint'),
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_owner', to='ShumiApp.profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='card',
            name='participants',
            field=models.ManyToManyField(blank=True, to='ShumiApp.Profile', verbose_name='Participants'),
        ),
        migrations.AddField(
            model_name='card',
            name='tag',
            field=models.ManyToManyField(blank=True, to='ShumiApp.Tag', verbose_name='Tag'),
        ),
    ]
