# Generated by Django 3.2.9 on 2021-11-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShumiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
    ]
